server:
  port: ${PORT:0}

spring:
  application:
    name: ms-spring-cloud-service
  profiles:
    active: local
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"


eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9999/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true